# Generated by Django 2.2.6 on 2019-10-26 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datavis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='url',
            new_name='image',
        ),
    ]
