# Generated by Django 2.2.6 on 2019-10-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datavis', '0002_auto_20191026_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_region', models.IntegerField(unique=True)),
                ('region', models.TextField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('count_people', models.IntegerField()),
                ('count_off', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
