# Generated by Django 2.2.6 on 2019-10-26 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datavis', '0003_auto_20191026_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='count_off',
        ),
        migrations.RemoveField(
            model_name='region',
            name='count_people',
        ),
    ]
